const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.join(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

test('model center backend api exposes provider options and model config management', () => {
  const providerController = read('src/modules/ai-platform/model-provider/model-provider.controller.ts')
  const providerService = read('src/modules/ai-platform/model-provider/model-provider.service.ts')
  const modelController = read('src/modules/ai-platform/model-config/model-config.controller.ts')
  const modelService = read('src/modules/ai-platform/model-config/model-config.service.ts')
  const moduleFile = read('src/modules/ai-platform/ai-platform.module.ts')
  const permissionSeed = read('prisma/seeds/permission.ts')
  const menuSeed = read('prisma/seeds/menu.ts')
  const menuMigration = read('prisma/migrations/20260804010000_add_ai_model_center_menu_permissions/migration.sql')
  const rolePermissionMigration = read('prisma/migrations/20260804020000_grant_ai_model_permissions_to_roles/migration.sql')

  assert.match(providerController, /Controller\('ai-platform\/model-provider'\)/)
  assert.match(providerController, /Get\('list'\)/)
  assert.match(providerController, /Get\('options'\)/)
  assert.match(providerService, /status:\s*1/)
  assert.match(modelController, /Controller\('ai-platform\/model'\)/)
  assert.match(modelController, /Post\('create'\)/)
  assert.match(modelController, /Post\('update'\)/)
  assert.match(modelController, /Post\('status'\)/)
  assert.match(modelService, /aiModelConfig\.updateMany/)
  assert.match(modelService, /modelType:\s*target\.modelType/)
  assert.match(modelService, /target\.isDefault\s*&&\s*target\.status\s*===\s*1/)
  assert.match(moduleFile, /ModelProviderController/)
  assert.match(moduleFile, /ModelConfigController/)
  assert.match(permissionSeed, /ai:model:list/)
  assert.match(menuSeed, /\/AIEngine\/model\/index/)
  assert.match(menuMigration, /ai:model:status/)
  assert.match(menuMigration, /MenuRole/)
  assert.match(rolePermissionMigration, /RolePermission/)
})
